### ISSUE TITLE
Wide review tracker

### ISSUE THREAD

**Issue by anssiko** [w3c/vibration#39]
> [!NOTE]
>This is a process issue to track [wide review](https://www.w3.org/2023/Process-20231103/#wide-review) for the Vibration API.
>
>An important part of wide review is horizontal review from W3C's [key horizontal groups](https://www.w3.org/Guide/documentreview/#how_to_get_horizontal_review) listed below in **horizontal groups** section. Also feedback from **other stakeholders** is equally important. Additional pointers are welcome via comments.
>
>Legend:
>⚪ Review request not submitted
>🟡 Review request submitted
>🔵 Review feedback received
>🟢 Review closed as completed

### Horizontal groups

🟢 ♿ **Accessibility** ([Accessible Platform Architectures Working Group](https://www.w3.org/WAI/about/groups/apawg/))
- [x] Work through the [a11y checklist](https://w3c.github.io/apa/fast/checklist.html): https://github.com/w3c/vibration/issues/37
- [x] [Request a review](https://github.com/w3c/a11y-request/issues/new/choose): https://github.com/w3c/a11y-request/issues/87

🟢 📐 **Architecture** ([Technical Architecture Group](https://www.w3.org/2001/tag/))
- [x] See [how to work with the TAG](https://tag.w3.org/workmode/)
- [x] [Request a review](https://github.com/w3ctag/design-reviews/issues/new/choose): https://github.com/w3ctag/design-reviews/issues/971 (draft staging issue archived at https://github.com/w3c/vibration/issues/40)

🟢 🌍 **Internationalization** ([Internationalization Working Group](https://www.w3.org/International/i18n-activity/i18n-wg/))
- [x] Read [how to request a review](https://www.w3.org/International/review-request)
- [x] Work through the [i18n checklist](https://www.w3.org/International/i18n-drafts/techniques/shortchecklist): https://github.com/w3c/vibration/issues/38
- [x] [Request a review](https://github.com/w3c/i18n-request/issues/new/choose): https://github.com/w3c/i18n-request/issues/236

🟢 🔍 **Privacy** ([Privacy Interest Group](https://www.w3.org/groups/ig/privacy/))
- [x] Write a "Privacy Considerations" section for your document, taking into account the [Self-Review Questionnaire: Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/), [Mitigating Browser Fingerprinting in Web Specifications](https://www.w3.org/TR/fingerprinting-guidance/), and [RFC6973](https://www.rfc-editor.org/rfc/rfc6973.html)
- [x] https://github.com/w3c/vibration/issues/36
- [x] [Request a review](https://github.com/w3cping/privacy-request/issues/new/choose): https://github.com/w3cping/privacy-request/issues/138

🟢 🔒 **Security**
- [x] Write a "Security Considerations" section for your document, taking into account the [Self-Review Questionnaire: Security and Privacy](https://www.w3.org/TR/security-privacy-questionnaire/)
- [x] https://github.com/w3c/vibration/issues/36
- [x] [Request a review](https://github.com/w3c/security-request/issues/new/choose): https://github.com/w3c/security-request/issues/71

### Other stakeholders

From [who to ask for review](https://www.w3.org/Guide/documentreview/#who_to_ask_for_review):
>Horizontal reviews [...] are only a subset of a full wide review, which must also include other stakeholders including Web developers, technology providers and implementers not active in the Working Group, external groups and standards organizations working on related areas, etc.

- Mozilla position: https://github.com/mozilla/standards-positions/issues/907
- WebKit position: https://github.com/WebKit/standards-positions/issues/267

**Comment by anssiko** [comment]
The following supplementary materials have been made available for the WG participants to review and comment:

- Accessibility: https://github.com/w3c/vibration/issues/37
- Internationalization: https://github.com/w3c/vibration/issues/38
- Security and Privacy: https://github.com/w3c/vibration/issues/36
- Architecture: https://github.com/w3c/vibration/issues/40

Accessibility, Internationalization and Security and Privacy issues will be linked from the respective horizontal review requests, so any comments provided in those issues will be brought to the attention of the horizontal groups.

**Comment by anssiko** [comment]
Thank you everyone for your feedback and comments that helped improve the supplementary materials significantly.

I have now submitted all the review request with a proposed deadline of 2024-09-20 to allow us discuss the wide review feedback at TPAC 2024.

Further improvements for Accessibility, Internationalization and Security and Privacy materials can be provided through respective issues in this repo. For Architecture/TAG review comments and improvements, please provide them directly in the upstream review request issue in the TAG repo.

You'll find pointers to all the review requests and materials from the first comment in this issue.

**Comment by anssiko** [comment]
Wide review has been completed.

Thank you everyone across all the horizontal groups for your diligent work in reviewing this specification! Your feedback improved the specification significantly.

What's next?

Following our [Call for Consensus](https://lists.w3.org/Archives/Public/public-device-apis/2024Jun/0006.html), we will execute the [resolution](https://www.w3.org/2024/09/24-dap-minutes.html#r03) we made at TPAC to publish this specification as a new Candidate Recommendation Snapshot, obsoleting the Second Edition Recommendation. This publication signals to the wider community the specification is both implemented and welcomes further implementation experience to inform improvements such as Permissions API integration (#42), security considerations (#49), and UI controls (#50).

@himorin thank you for handling the remaining logistics required to get this publication out.
